#!/bin/sh
#
# PROVIDE: bogofilterd
# REQUIRE: DAEMON
# BEFORE:  mail
#
#
# You will need to set some variables in /etc/rc.conf to start sobermailfilter:
#
# bogofilterd=YES
#
# The following variables are optional:
#
#					# before starting amavisd

if [ -f /etc/rc.subr ]; then
	. /etc/rc.subr
fi

export PATH="$PATH:/sbin:/usr/sbin:/usr/pkg/bin:/usr/pkg/sbin"

name="bogofilterd"
rcvar=$name
command="/usr/pkg/sbin/bogofilter-daemon.py"
pidfile="/var/run/${name}.pid"
logfile="/var/log/bogofilterd.log"
dircfg="/usr/pkg/etc"
required_files="${dircfg}/bogofilter-daemon.conf"
user="vscan"
group="vscan"

start_precmd="bogofilterd_prestart"
start_cmd="bogofilterd_start"
stop_cmd="bogofilterd_stop"
status_cmd="bogofilterd_status"

bogofilterd_prestart()
{
    [ ! -d /var/db/bogofilter ] && ( mkdir -p /var/db/bogofilter ; chown ${user} /var/db/bogofilter )
    [ ! -d /var/amavis/.bogofilter ] && ( mkdir -p /var/amavis/.bogofilter ; chown ${user} /var/amavis/.bogofilter >/dev/null 2>&1 )
    [ ! -d /dev/shm/bogofilter-daemon ] && ( mkdir -p /dev/shm/bogofilter-daemon ; chown ${user} /dev/shm/bogofilter-daemon >/dev/null 2>&1 )
    [ ! -e /var/amavis/.bogofilter/wordlist.db ] && ( su - ${user} -c "bogofilter -n -I /etc/passwd" ; su - ${user} -c "bogofilter -s -I /etc/group" )
    chown ${user}:${group} /var/amavis/.bogofilter/wordlist.db
    chmod 664 /var/amavis/.bogofilter/wordlist.db
    return 0
}

check_pid()
{
	PID=`cat ${pidfile} 2>/dev/null`
	if [ -n "`ps --no-headers -p ${PID} 2>/dev/null`" ] 
	then
		echo "1"
	else
		echo "0"
	fi
}


bogofilterd_start()
{
	if [ $(check_pid) -eq 1 ] 
	then
		echo "$name is running"
		exit 1
	fi
	echo "initialize at `date +%c`" >> ${logfile}
	${command} >>${logfile} 2>&1 &
	echo $! > ${pidfile}
	if [ $(check_pid) -eq 0 ]
	then
		echo "$name isn't initialized correctly."
		exit 1 
	fi
	echo "$name initialized"
	exit 0
}

bogofilterd_stop()
{
	[ -e ${pidfile} ] && (
		echo -n "Stopping ${name}:"
	        while kill -9 `cat ${pidfile}` >/dev/null 2>&1
		do	
			echo -n '.'
		done
		echo ' STOPPED '
		rm -f ${pidfile} 2>/dev/null
		echo "stopped at `date +%c`" >> ${logfile}
	)
}

bogofilterd_status()
{
	if [ $(check_pid) -eq 1 ] 
	then
		echo "$name - main process is started" 
	else
		echo "$name - main process isn't started" 
	fi
}
if [ -f /etc/rc.subr -a -f /etc/rc.conf \
     -a -d /etc/rc.d ]; then
	load_rc_config $name
	run_rc_command ${1}
else
	echo "Isn't possible to start $name"
fi
