#!/bin/sh
#
# PROVIDE: sobermailfilter
# REQUIRE: DAEMON
# BEFORE:  mail bogofilterd
#
#
# You will need to set some variables in /etc/rc.conf to start sobermailfilter:
#
# sobermailfilter=YES
#
# The following variables are optional:
#
#					# before starting amavisd

if [ -f /etc/rc.subr ]; then
	. /etc/rc.subr
fi

export PATH="$PATH:/sbin:/usr/sbin:/usr/pkg/bin:/usr/pkg/sbin"

name="sobermailfilter"
rcvar=$name
command="/usr/pkg/etc/sobermailfilter/${name}.pyc"
cmd_interpreter="/usr/pkg/bin/python2.6"
pidfile="/var/run/sobermailfilter.pid"
logfile="/var/log/sobermailfilter.log"
dircfg="/usr/pkg/etc/sobermailfilter"
required_files="${dircfg}/sober.cfg"
sober_mod="enqueuer-in policyd scanner enqueuer-out webservice"
soberdir="/var/sober"
queuedir="${soberdir}/queue"
quarantinedir="${soberdir}/quarantine"
antispamdir="${soberdir}/antispam"
bogodir="/var/amavis/.bogofilter"
user="vscan"
group="vscan"
sober_mod="enqueuer-in policyd scanner enqueuer-out webservice"

changeperms_cmd="sobermailfilter_changeperms"
start_precmd="sobermailfilter_prestart"
reload_cmd="sobermailfilter_reload"
start_cmd="sobermailfilter_start"
stop_cmd="sobermailfilter_stop"
status_cmd="sobermailfilter_status"
extra_commands="reload changeperms"

sobermailfilter_changeperms()
{
    /bin/mkdir -p ${antispamdir}/{a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z}/{a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z}
    /bin/chmod -R 0770 ${queuedir} ${quarantinedir} ${antispamdir} ${bogodir} &
    /bin/chown -R ${user}:${group} ${queuedir} ${quarantinedir} ${antispamdir} ${bogodir} &
}

sobermailfilter_prestart(){
    for i in ${queuedir} ${quarantinedir} ${antispamdir}
    do
        /bin/mkdir -p ${i}/{0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z}/{0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z}
    done
    cd $dircfg
}

check_pid()
{
	PID=`cat ${pidfile} 2>/dev/null`
	if [ -n "`ps --no-headers -p ${PID} 2>/dev/null`" ] 
	then
		echo "1"
	else
		echo "0"
	fi
}


sobermailfilter_start()
{
	if [ $(check_pid) -eq 1 ] 
	then
		echo "$name is running"
		exit 1
	fi
	echo "initialize at `date +%c`" >> ${logfile}
	${cmd_interpreter} ${command} >>${logfile} 2>&1 &
	echo $! > ${pidfile}
	if [ $(check_pid) -eq 0 ]
	then
		echo "$name isn't initialized correctly."
		exit 1 
	fi
	echo "$name initialized"
	exit 0
}

sobermailfilter_stop()
{
	[ -e ${pidfile} ] && (
		echo -n "Stopping ${name}:"
	        while kill -9 `cat ${pidfile}` >/dev/null 2>&1
		do	
			echo -n '.'
		done
	        while kill -9 `pgrep -f ${dircfg}` `for i in ${sober_mod} ; do pgrep -f "sober \(${i}" ; done ` >/dev/null 2>&1
		do	
			echo -n '.'
		done
		echo ' STOPPED '
		rm ${pidfile}
		echo "stopped at `date +%c`" >> ${logfile}
	)
}

sobermailfilter_reload(){
    cd $dircfg
    sobermailfilter_stop
    sleep 1
    sobermailfilter_start
}

sobermailfilter_status()
{
	if [ $(check_pid) -eq 1 ] 
	then
		echo "$name - main process is started" 
	else
		echo "$name - main process isn't started" 
	fi
	for i in ${sober_mod}
	do
		if [ -n "`pgrep -f "sober \(${i}"`" ]
		then
	 		echo "$name - process $i is started" 
		else
			echo "$name - process $i isn't started" 
		fi
	done
}
if [ -f /etc/rc.subr -a -f /etc/rc.conf \
     -a -d /etc/rc.d ]; then
	load_rc_config $name
	run_rc_command ${1}
else
	echo "Isn't possible to start $name"
fi
